# Tomcat
server:
  tomcat:
    threads:
      max: 10
      min-spare: 10
  port: 8981

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.70:3306/auto_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: dev
    password: sunxing321
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

# Mybatis
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

